# Form implementation generated from reading ui file 'wind.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1033, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1033, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_map = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_map.setGeometry(QtCore.QRect(130, 150, 600, 380))
        self.label_map.setMinimumSize(QtCore.QSize(600, 380))
        self.label_map.setMaximumSize(QtCore.QSize(600, 380))
        self.label_map.setStyleSheet("QLabel{\n"
"    color: rgb(3, 3, 3);\n"
"    border: 3px solid rgb(126, 126, 126);\n"
"}")
        self.label_map.setText("")
        self.label_map.setObjectName("label_map")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(640, 40, 352, 62))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.points_1 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.points_1.setFont(font)
        self.points_1.setObjectName("points_1")
        self.verticalLayout.addWidget(self.points_1)
        self.points_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.points_2.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.points_2.setFont(font)
        self.points_2.setObjectName("points_2")
        self.verticalLayout.addWidget(self.points_2)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 40, 610, 64))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.answer_line_edit = QtWidgets.QLineEdit(parent=self.widget)
        self.answer_line_edit.setMinimumSize(QtCore.QSize(250, 0))
        self.answer_line_edit.setObjectName("answer_line_edit")
        self.horizontalLayout.addWidget(self.answer_line_edit)
        self.answer_btn = QtWidgets.QPushButton(parent=self.widget)
        self.answer_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.answer_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(227, 227, 227);\n"
"    color: rgb(3, 3, 3);\n"
"    border: 2px solid rgb(126, 126, 126);\n"
"    border-radius: 2px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4CAF50;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.answer_btn.setObjectName("answer_btn")
        self.horizontalLayout.addWidget(self.answer_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.no_answer = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.no_answer.setFont(font)
        self.no_answer.setText("")
        self.no_answer.setObjectName("no_answer")
        self.verticalLayout_2.addWidget(self.no_answer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.points_1.setText(_translate("MainWindow", "Игрок номер 1: "))
        self.points_2.setText(_translate("MainWindow", "Игрок номер 2: "))
        self.label_2.setText(_translate("MainWindow", "Игрок номер 1 ваш ответ: "))
        self.answer_btn.setText(_translate("MainWindow", "  Отправить  "))
